# Generated by Django 6.1.2 on 2026-10-09 03:28

import django.utils.timezone
import gio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('CAMBIO_ESTATUS', 'Cambio de estatus'), ('ASIGNACION', 'Asignación'), ('LIQUIDACION', 'Liquidación'), ('EVIDENCIA', 'Carga de evidencia'), ('INGESTA', 'Ingesta SISA'), ('EXPORTACION', 'Exportación SISA')], max_length=20)),
                ('campo', models.CharField(blank=True, default='', max_length=60)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'registro de bitácora',
                'verbose_name_plural': 'bitácora de incidentes',
                'db_table': 'incidentes_bitacora',
                'ordering': ['-registrado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=gio_app.models.ruta_evidencia)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('coordenadas_gps', models.CharField(blank=True, default='', max_length=60)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('fecha_captura', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'db_table': 'incidentes_evidencias',
                'ordering': ['-fecha_captura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('incidente', models.CharField(blank=True, default='', max_length=50)),
                ('referencia', models.CharField(blank=True, default='', max_length=50)),
                ('empresa', models.CharField(blank=True, default='', max_length=150)),
                ('tipo_servicio', models.CharField(blank=True, default='', max_length=50)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('LIQUIDADO', 'Liquidado')], db_index=True, default='PENDIENTE', max_length=15)),
                ('codigo_fallo', models.CharField(blank=True, choices=[('F1', 'F1 — Familia de falla'), ('COD4', 'COD4 — Causa raíz'), ('CARLS', 'CARLS — Diagnóstico'), ('COD5', 'COD5 — Acción correctiva')], default='', max_length=10)),
                ('estado_enlace', models.CharField(choices=[('UP', 'UP (en línea)'), ('DOWN', 'DOWN (caído)'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=15)),
                ('fecha_apertura', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('dilacion_dias', models.IntegerField(db_index=True, default=0)),
                ('area_operativa', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('central', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('cope', models.CharField(blank=True, default='', max_length=100)),
                ('ctro_trabajo', models.CharField(blank=True, default='', max_length=100)),
                ('oqu', models.CharField(blank=True, default='', max_length=100)),
                ('telefono_tecnico', models.CharField(blank=True, default='', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('diagnostico_final', models.TextField(blank=True, default='')),
                ('obs_usuario', models.TextField(blank=True, default='')),
                ('observaciones_sisa', models.TextField(blank=True, default='')),
                ('dir_pta_a', models.TextField(blank=True, default='')),
                ('punta_a', models.CharField(blank=True, default='', max_length=100)),
                ('ips', models.CharField(blank=True, default='', max_length=50)),
                ('dslam', models.CharField(blank=True, default='', max_length=100)),
                ('red_secundaria', models.CharField(blank=True, default='', max_length=100)),
                ('desc_f1', models.CharField(blank=True, default='', max_length=255)),
                ('desc_cod4', models.CharField(blank=True, default='', max_length=255)),
                ('desc_carls', models.CharField(blank=True, default='', max_length=255)),
                ('desc_cod5', models.CharField(blank=True, default='', max_length=255)),
                ('cve_liq', models.CharField(blank=True, default='', max_length=50)),
                ('desc_liq', models.TextField(blank=True, default='')),
                ('leyenda_sisa', models.CharField(blank=True, default='', max_length=100)),
                ('exportado_sisa', models.BooleanField(db_index=True, default=False)),
                ('estado_sincronizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de exportar'), ('EXPORTADO', 'Exportado a SISA'), ('ERROR', 'Error de sincronización')], default='PENDIENTE', max_length=30)),
                ('ultimo_intento_sinc', models.DateTimeField(blank=True, null=True)),
                ('error_sincronizacion', models.TextField(blank=True, default='')),
                ('origen_sisa', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'db_table': 'incidentes_red',
                'ordering': ['-fecha_apertura', '-id'],
            },
        ),
    ]
