# Generated by Django 6.1.1 on 2026-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incidente', models.CharField(blank=True, max_length=50, null=True)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('obs_usuario', models.TextField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('area_operativa', models.CharField(blank=True, max_length=100, null=True)),
                ('dilacion_dias', models.IntegerField(blank=True, null=True)),
                ('central', models.CharField(help_text='Nombre de la central (Ej. Puebla Centro)', max_length=100)),
                ('tipo_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_pta_a', models.TextField(blank=True, null=True)),
                ('punta_a', models.CharField(blank=True, max_length=100, null=True)),
                ('ctro_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_f1', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_sisa', models.TextField(blank=True, null=True)),
                ('desc_cod4', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_carls', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_cod5', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_tecnico', models.CharField(blank=True, max_length=20, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('estatus_io', models.CharField(blank=True, max_length=10, null=True)),
                ('cope', models.CharField(blank=True, max_length=100, null=True)),
                ('red_secundaria', models.CharField(blank=True, max_length=100, null=True)),
                ('dslam', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_qp', models.CharField(blank=True, max_length=20, null=True)),
                ('cve_liq', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_liq', models.TextField(blank=True, null=True)),
                ('leyenda_sisa', models.CharField(blank=True, max_length=100, null=True)),
                ('oqu', models.CharField(blank=True, max_length=100, null=True)),
                ('actualizado_por_gio', models.BooleanField(blank=True, default=True, null=True)),
                ('estado_sincronizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('ultimo_intento_sinc', models.DateTimeField(blank=True, null=True)),
                ('error_sincronizacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidentes_red',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
