# Generated by Django 6.1.1 on 2026-09-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('incidente', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.CharField(max_length=150)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('ctro_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_tecnico', models.CharField(blank=True, max_length=20, null=True)),
                ('punta_a', models.CharField(blank=True, max_length=100, null=True)),
                ('dir_pta_a', models.CharField(blank=True, max_length=200, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('dslam', models.CharField(blank=True, max_length=100, null=True)),
                ('cope', models.CharField(blank=True, max_length=100, null=True)),
                ('red_secundaria', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_io', models.CharField(default='PENDIENTE', max_length=50)),
                ('estatus_qp', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('dilacion', models.IntegerField(default=0)),
                ('cve_liq', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_liq', models.CharField(blank=True, max_length=200, null=True)),
                ('oqu', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_f1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_cod4', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_carls', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_cod5', models.CharField(blank=True, max_length=200, null=True)),
                ('obs_usuario', models.TextField(blank=True, null=True)),
                ('leyenda_sisa', models.TextField(blank=True, null=True)),
                ('observaciones_sisa', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_por_gio', models.BooleanField(default=False)),
                ('central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='gio_app.central')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='gio_app.tecnico')),
            ],
            options={
                'db_table': 'incidentes_red',
                'ordering': ['-fecha_ingreso', '-id'],
            },
        ),
    ]
