# Generated by Django 6.1.1 on 2026-09-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Central',
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
