# Generated by Django 6.1.2 on 2026-10-09 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gio_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraincidente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciaincidente',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_evaluados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciaincidente',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='gio_app.incidente'),
        ),
        migrations.AddField(
            model_name='bitacoraincidente',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='gio_app.incidente'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['estatus', 'exportado_sisa'], name='incidentes__estatus_1a1dee_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['tecnico', 'estatus'], name='incidentes__tecnico_42f5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['evaluador', 'estatus'], name='incidentes__evaluad_a11130_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estatus', 'LIQUIDADO'), ('fecha_cierre__isnull', False)), models.Q(('estatus', 'LIQUIDADO'), _negated=True), _connector='OR'), name='liquidado_requiere_fecha_cierre'),
        ),
    ]
