# Generated by Django 6.1.2 on 2026-10-09 03:28

import django.core.validators
import django.utils.timezone
import usuarios.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioGIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('expediente', models.CharField(help_text='Identificador corporativo de acceso (Ej. OQU-8821).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9._-]{3,20}$', 'El expediente admite letras, dígitos, punto, guion y guion bajo.')])),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('rol', models.CharField(choices=[('TECNICO', 'Planta Externa (Técnico)'), ('PI_EVALUADOR', 'Planta Interna (Evaluador)'), ('PI_SUB', 'Planta Interna (Subgerencia)'), ('ADMIN', 'Gerencia / Administración')], db_index=True, default='TECNICO', max_length=20)),
                ('area_operativa', models.CharField(blank=True, choices=[('PUEBLA', 'Puebla'), ('PACHUCA', 'Pachuca'), ('VERACRUZ', 'Veracruz'), ('POZA RICA', 'Poza Rica'), ('XALAPA', 'Xalapa'), ('TLAXCALA', 'Tlaxcala'), ('CORDOBA', 'Córdoba'), ('COATZACOALCOS', 'Coatzacoalcos')], default='', max_length=50)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario GIO',
                'verbose_name_plural': 'usuarios GIO',
                'ordering': ['expediente'],
            },
            managers=[
                ('objects', usuarios.managers.UsuarioGIOManager()),
            ],
        ),
    ]
